STATUS_UPLOADING = 1000
STATUS_UPLOADED = 1002
STATUS_QUEUED = 1003
STATUS_PROCESSING = 1101
STATUS_PROCESSED = 1200
STATUS_FAILED = 1301

ALLOWED_STATUS_CODES = (
    STATUS_UPLOADING,
    STATUS_UPLOADED,
    STATUS_QUEUED,
    STATUS_PROCESSING,
    STATUS_PROCESSED,
    STATUS_FAILED,
)
